// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class AcademicYear
    {
        public AcademicYear()
        {
            InstituteClass = new HashSet<InstituteClass>();
            InstituteUserClass = new HashSet<InstituteUserClass>();
        }

        public long Id { get; set; }
        public int AcademicYear1 { get; set; }
        public long InstituteId { get; set; }
        public bool? IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual Institute Institute { get; set; }
        public virtual ICollection<InstituteClass> InstituteClass { get; set; }
        public virtual ICollection<InstituteUserClass> InstituteUserClass { get; set; }
    }
}