// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class CalenderEvent
    {
        public long Id { get; set; }
        public string SubjectName { get; set; }
        public string DescriptionText { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public int EventTypeId { get; set; }
        public long InstituteUserId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual EventType EventType { get; set; }
        public virtual InstituteUser InstituteUser { get; set; }
    }
}