// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class ContactType
    {
        public ContactType()
        {
            UserContact = new HashSet<UserContact>();
        }

        public int Id { get; set; }
        public string TypeText { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual ICollection<UserContact> UserContact { get; set; }
    }
}