// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class ContextType
    {
        public ContextType()
        {
            InstituteAssignment = new HashSet<InstituteAssignment>();
        }

        public int Id { get; set; }
        public string ContextType1 { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual ICollection<InstituteAssignment> InstituteAssignment { get; set; }
    }
}