// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class IncidentReport
    {
        public long Id { get; set; }
        public long InstituteId { get; set; }
        public long InstituteUserId { get; set; }
        public DateTime RecordDate { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public long ResponsibleUserId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }
    }
}