// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class Insitute
    {
        public Insitute()
        {
            InsituteUser = new HashSet<InsituteUser>();
        }

        public Guid Id { get; set; }
        public string InsituteName { get; set; }
        public string InsituteAddess { get; set; }
        public Guid? PackageId { get; set; }
        public Guid? CountryId { get; set; }
        public bool? IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual Country Country { get; set; }
        public virtual Package Package { get; set; }
        public virtual ICollection<InsituteUser> InsituteUser { get; set; }
    }
}