// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class InstituteCommunicationTemplate
    {
        public long Id { get; set; }
        public string TemplateName { get; set; }
        public string TemplateContent { get; set; }
        public long InstituteId { get; set; }
        public bool IsSenderTemplate { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }
    }
}