// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class InstituteCommunication
    {
        public long Id { get; set; }
        public string Subject { get; set; }
        public int CommunicationType { get; set; }
        public string Message { get; set; }
        public DateTime SendDate { get; set; }
        public long FromUserid { get; set; }
        public string CommunicationSourceId { get; set; }
        public long? AssociatedCommunicationId { get; set; }
        public long InstituteId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }
    }
}