// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class InstitutePrefix
    {
        public long Id { get; set; }
        public string PrefixCode { get; set; }
        public string PrefixValue { get; set; }
        public long NextNumber { get; set; }
        public long InstituteId { get; set; }
        public string PrefixType { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }
    }
}