// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class InstituteUser
    {
        public InstituteUser()
        {
            CalenderEvent = new HashSet<CalenderEvent>();
            InstituteAssignmentSubmission = new HashSet<InstituteAssignmentSubmission>();
            InstituteClass = new HashSet<InstituteClass>();
            InstituteClassSubject = new HashSet<InstituteClassSubject>();
            InstituteExam = new HashSet<InstituteExam>();
            InstituteExemptDependUserDependInstituteUser = new HashSet<InstituteExemptDependUser>();
            InstituteExemptDependUserExemptInstituteUser = new HashSet<InstituteExemptDependUser>();
            InstituteUserClass = new HashSet<InstituteUserClass>();
            SupportTicket = new HashSet<SupportTicket>();
        }

        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long UserIdx { get; set; }
        public int RoleId { get; set; }
        public long InstituteId { get; set; }
        public long? StudentUserId { get; set; }
        public long? ParentUserid { get; set; }
        public long? ClassTeacherUserId { get; set; }
        public long? HeadTeacherUserId { get; set; }
        public long? CommunicationGroup { get; set; }
        public string Username { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Password { get; set; }
        public string ImageUrl { get; set; }
        public bool? IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual Institute Institute { get; set; }
        public virtual Role Role { get; set; }
        public virtual User UserIdxNavigation { get; set; }
        public virtual ICollection<CalenderEvent> CalenderEvent { get; set; }
        public virtual ICollection<InstituteAssignmentSubmission> InstituteAssignmentSubmission { get; set; }
        public virtual ICollection<InstituteClass> InstituteClass { get; set; }
        public virtual ICollection<InstituteClassSubject> InstituteClassSubject { get; set; }
        public virtual ICollection<InstituteExam> InstituteExam { get; set; }
        public virtual ICollection<InstituteExemptDependUser> InstituteExemptDependUserDependInstituteUser { get; set; }
        public virtual ICollection<InstituteExemptDependUser> InstituteExemptDependUserExemptInstituteUser { get; set; }
        public virtual ICollection<InstituteUserClass> InstituteUserClass { get; set; }
        public virtual ICollection<SupportTicket> SupportTicket { get; set; }
    }
}