// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class InstituteTerm
    {
        public InstituteTerm()
        {
            InstituteExam = new HashSet<InstituteExam>();
            InstituteTermChapter = new HashSet<InstituteTermChapter>();
        }

        public long Id { get; set; }
        public string Term { get; set; }
        public long InstituteId { get; set; }
        public bool? IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual Institute Institute { get; set; }
        public virtual ICollection<InstituteExam> InstituteExam { get; set; }
        public virtual ICollection<InstituteTermChapter> InstituteTermChapter { get; set; }
    }
}