// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class InstituteClass
    {
        public InstituteClass()
        {
            InstituteClassSubject = new HashSet<InstituteClassSubject>();
            InstituteUserClass = new HashSet<InstituteUserClass>();
        }

        public long Id { get; set; }
        public string Class { get; set; }
        public long InstituteId { get; set; }
        public long AcademicYearId { get; set; }
        public long ResponsibleUserId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual AcademicYear AcademicYear { get; set; }
        public virtual Institute Institute { get; set; }
        public virtual InstituteUser ResponsibleUser { get; set; }
        public virtual ICollection<InstituteClassSubject> InstituteClassSubject { get; set; }
        public virtual ICollection<InstituteUserClass> InstituteUserClass { get; set; }
    }
}