// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class InstituteAssignment
    {
        public InstituteAssignment()
        {
            InstituteAssignmentDocument = new HashSet<InstituteAssignmentDocument>();
            InstituteAssignmentSubmission = new HashSet<InstituteAssignmentSubmission>();
            InstituteChapterTopic = new HashSet<InstituteChapterTopic>();
            InstituteSubjectChapter = new HashSet<InstituteSubjectChapter>();
        }

        public long Id { get; set; }
        public string AssignmentTitle { get; set; }
        public string AssignmentDescription { get; set; }
        public DateTime OpenDate { get; set; }
        public DateTime CloseDate { get; set; }
        public bool? IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual ICollection<InstituteAssignmentDocument> InstituteAssignmentDocument { get; set; }
        public virtual ICollection<InstituteAssignmentSubmission> InstituteAssignmentSubmission { get; set; }
        public virtual ICollection<InstituteChapterTopic> InstituteChapterTopic { get; set; }
        public virtual ICollection<InstituteSubjectChapter> InstituteSubjectChapter { get; set; }
    }
}