// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class InstituteAssignment
    {
        public InstituteAssignment()
        {
            InstituteAssignmentSubmission = new HashSet<InstituteAssignmentSubmission>();
        }

        public long Id { get; set; }
        public string Assignment { get; set; }
        public long ContextId { get; set; }
        public int ContextTypeId { get; set; }
        public long ResponsibleUserId { get; set; }
        public DateTime OpenDate { get; set; }
        public DateTime CloseDate { get; set; }
        public bool? IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual ContextType ContextType { get; set; }
        public virtual InstituteUser ResponsibleUser { get; set; }
        public virtual ICollection<InstituteAssignmentSubmission> InstituteAssignmentSubmission { get; set; }
    }
}