// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class InstituteClassTimeTable
    {
        public long Id { get; set; }
        public long InstituteClassId { get; set; }
        public long InstituteClassSubjectId { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public int? WeekDayId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }
    }
}