// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class InstituteUserClass
    {
        public long Id { get; set; }
        public long InstituteUserId { get; set; }
        public long InstituteClassId { get; set; }
        public long AcademicYearId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual AcademicYear AcademicYear { get; set; }
        public virtual InstituteClass InstituteClass { get; set; }
        public virtual InstituteUser InstituteUser { get; set; }
    }
}