// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class InstituteClassSubject
    {
        public InstituteClassSubject()
        {
            InstituteExam = new HashSet<InstituteExam>();
            InstituteSubjectChapter = new HashSet<InstituteSubjectChapter>();
        }

        public long Id { get; set; }
        public long InstituteClassId { get; set; }
        public long InstituteSubjectId { get; set; }
        public long ResponsibleUserId { get; set; }
        public string BgColor { get; set; }
        public string FontColor { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual InstituteClass InstituteClass { get; set; }
        public virtual InstituteSubject InstituteSubject { get; set; }
        public virtual InstituteUser ResponsibleUser { get; set; }
        public virtual ICollection<InstituteExam> InstituteExam { get; set; }
        public virtual ICollection<InstituteSubjectChapter> InstituteSubjectChapter { get; set; }
    }
}