// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class InstituteTopicContentDocument
    {
        public long Id { get; set; }
        public long InstituteTopicContentId { get; set; }
        public string FileName { get; set; }
        public string EncryptedFileName { get; set; }
        public string ContentUrl { get; set; }
        public bool? IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual InstituteTopicContent InstituteTopicContent { get; set; }
    }
}