// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class InstituteAssignmentSubmission
    {
        public long Id { get; set; }
        public long InstituteAssignmentId { get; set; }
        public long SubmitUserId { get; set; }
        public DateTime SubmitDate { get; set; }
        public string DocumentUrl { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual InstituteAssignment InstituteAssignment { get; set; }
        public virtual InstituteUser SubmitUser { get; set; }
    }
}