// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class InstituteExam
    {
        public InstituteExam()
        {
            InstituteExamSubmission = new HashSet<InstituteExamSubmission>();
        }

        public long Id { get; set; }
        public string Exam { get; set; }
        public long InstituteTermId { get; set; }
        public long InstituteClassSubjectId { get; set; }
        public long ResponsibleUserId { get; set; }
        public DateTime OpenDate { get; set; }
        public DateTime CloseDate { get; set; }
        public bool? IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual InstituteClassSubject InstituteClassSubject { get; set; }
        public virtual InstituteTerm InstituteTerm { get; set; }
        public virtual InstituteUser ResponsibleUser { get; set; }
        public virtual ICollection<InstituteExamSubmission> InstituteExamSubmission { get; set; }
    }
}