// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class InstituteChapterTopic
    {
        public InstituteChapterTopic()
        {
            InstituteTopicContent = new HashSet<InstituteTopicContent>();
        }

        public long Id { get; set; }
        public string Topic { get; set; }
        public string DescriptionText { get; set; }
        public long InstituteSubjectChapterId { get; set; }
        public long? InstituteAssignmentId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual InstituteAssignment InstituteAssignment { get; set; }
        public virtual InstituteSubjectChapter InstituteSubjectChapter { get; set; }
        public virtual ICollection<InstituteTopicContent> InstituteTopicContent { get; set; }
    }
}