// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class InstituteInvoice
    {
        public long Id { get; set; }
        public string InvoiceNo { get; set; }
        public DateTime InvoiceDate { get; set; }
        public DateTime DueDate { get; set; }
        public string InvoiceTitle { get; set; }
        public string InvoiceDetails { get; set; }
        public int StatusId { get; set; }
        public decimal InvoiceAmount { get; set; }
        public long InstituteId { get; set; }
        public long InvoiceTypeId { get; set; }
        public long? GeneratedBy { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }
    }
}