// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class InstituteTopicContent
    {
        public InstituteTopicContent()
        {
            InstituteTopicContentDocument = new HashSet<InstituteTopicContentDocument>();
        }

        public long Id { get; set; }
        public long InstituteChapterTopicId { get; set; }
        public int ContentTypeId { get; set; }
        public string ContentText { get; set; }
        public int ContentOrder { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual ContentType ContentType { get; set; }
        public virtual InstituteChapterTopic InstituteChapterTopic { get; set; }
        public virtual ICollection<InstituteTopicContentDocument> InstituteTopicContentDocument { get; set; }
    }
}