// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class Module
    {
        public Module()
        {
            PackageModule = new HashSet<PackageModule>();
            RoleModule = new HashSet<RoleModule>();
        }

        public long Id { get; set; }
        public string ModuleName { get; set; }
        public bool? IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual ICollection<PackageModule> PackageModule { get; set; }
        public virtual ICollection<RoleModule> RoleModule { get; set; }
    }
}