// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class Package
    {
        public Package()
        {
            Institute = new HashSet<Institute>();
            PackageModule = new HashSet<PackageModule>();
        }

        public Guid Id { get; set; }
        public string PackageName { get; set; }
        public bool? IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual ICollection<Institute> Institute { get; set; }
        public virtual ICollection<PackageModule> PackageModule { get; set; }
    }
}