// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class PackageModule
    {
        public long Id { get; set; }
        public int PackageId { get; set; }
        public long ModuleId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual Module Module { get; set; }
        public virtual Package Package { get; set; }
    }
}