// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace ParentCheck.Data
{
    public partial class ParentCheckContext : DbContext
    {
        public ParentCheckContext()
        {
        }

        public ParentCheckContext(DbContextOptions<ParentCheckContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ContactType> ContactType { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Institute> Institute { get; set; }
        public virtual DbSet<InstituteUser> InstituteUser { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<Package> Package { get; set; }
        public virtual DbSet<PackageModule> PackageModule { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleModule> RoleModule { get; set; }
        public virtual DbSet<SystemUser> SystemUser { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserContact> UserContact { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<ContactType>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.ContactTypeName)
                    .HasMaxLength(100)
                    .HasColumnName("contactTypeName");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("createdBy");

                entity.Property(e => e.CreatedOn)
                    .HasColumnType("datetime")
                    .HasColumnName("createdOn");

                entity.Property(e => e.UpdateOn)
                    .HasColumnType("datetime")
                    .HasColumnName("updateOn");

                entity.Property(e => e.UpdatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("updatedBy");
            });

            modelBuilder.Entity<Country>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.CountryName)
                    .HasMaxLength(100)
                    .HasColumnName("countryName");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("createdBy");

                entity.Property(e => e.CreatedOn)
                    .HasColumnType("datetime")
                    .HasColumnName("createdOn");

                entity.Property(e => e.IsActive).HasColumnName("isActive");

                entity.Property(e => e.UpdateOn)
                    .HasColumnType("datetime")
                    .HasColumnName("updateOn");

                entity.Property(e => e.UpdatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("updatedBy");
            });

            modelBuilder.Entity<Institute>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.CountryId).HasColumnName("countryId");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("createdBy");

                entity.Property(e => e.CreatedOn)
                    .HasColumnType("datetime")
                    .HasColumnName("createdOn");

                entity.Property(e => e.InstituteAddess)
                    .HasMaxLength(250)
                    .HasColumnName("instituteAddess");

                entity.Property(e => e.InstituteName)
                    .HasMaxLength(200)
                    .HasColumnName("instituteName");

                entity.Property(e => e.IsActive).HasColumnName("isActive");

                entity.Property(e => e.PackageId).HasColumnName("packageId");

                entity.Property(e => e.UpdateOn)
                    .HasColumnType("datetime")
                    .HasColumnName("updateOn");

                entity.Property(e => e.UpdatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("updatedBy");

                entity.HasOne(d => d.Country)
                    .WithMany(p => p.Institute)
                    .HasForeignKey(d => d.CountryId)
                    .HasConstraintName("FK_Institute_Country");

                entity.HasOne(d => d.Package)
                    .WithMany(p => p.Institute)
                    .HasForeignKey(d => d.PackageId)
                    .HasConstraintName("FK_Institute_Package");
            });

            modelBuilder.Entity<InstituteUser>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("createdBy");

                entity.Property(e => e.CreatedOn)
                    .HasColumnType("datetime")
                    .HasColumnName("createdOn");

                entity.Property(e => e.InstituteId).HasColumnName("instituteId");

                entity.Property(e => e.IsActive).HasColumnName("isActive");

                entity.Property(e => e.Password)
                    .HasMaxLength(200)
                    .HasColumnName("password");

                entity.Property(e => e.RoleId).HasColumnName("roleId");

                entity.Property(e => e.UpdateOn)
                    .HasColumnType("datetime")
                    .HasColumnName("updateOn");

                entity.Property(e => e.UpdatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("updatedBy");

                entity.Property(e => e.UserId).HasColumnName("userId");

                entity.HasOne(d => d.Institute)
                    .WithMany(p => p.InstituteUser)
                    .HasForeignKey(d => d.InstituteId)
                    .HasConstraintName("FK_InstituteUser_Institute");

                entity.HasOne(d => d.Role)
                    .WithMany(p => p.InstituteUser)
                    .HasForeignKey(d => d.RoleId)
                    .HasConstraintName("FK_InstituteUser_Role");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.InstituteUser)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK_InstituteUser_User");
            });

            modelBuilder.Entity<Module>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("createdBy");

                entity.Property(e => e.CreatedOn)
                    .HasColumnType("datetime")
                    .HasColumnName("createdOn");

                entity.Property(e => e.IsActive).HasColumnName("isActive");

                entity.Property(e => e.ModuleName)
                    .HasMaxLength(100)
                    .HasColumnName("moduleName");

                entity.Property(e => e.UpdateOn)
                    .HasColumnType("datetime")
                    .HasColumnName("updateOn");

                entity.Property(e => e.UpdatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("updatedBy");
            });

            modelBuilder.Entity<Package>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("createdBy");

                entity.Property(e => e.CreatedOn)
                    .HasColumnType("datetime")
                    .HasColumnName("createdOn");

                entity.Property(e => e.IsActive).HasColumnName("isActive");

                entity.Property(e => e.PackageName)
                    .HasMaxLength(100)
                    .HasColumnName("packageName");

                entity.Property(e => e.UpdateOn)
                    .HasColumnType("datetime")
                    .HasColumnName("updateOn");

                entity.Property(e => e.UpdatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("updatedBy");
            });

            modelBuilder.Entity<PackageModule>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("createdBy");

                entity.Property(e => e.CreatedOn)
                    .HasColumnType("datetime")
                    .HasColumnName("createdOn");

                entity.Property(e => e.ModuleId).HasColumnName("moduleId");

                entity.Property(e => e.PackageId).HasColumnName("packageId");

                entity.Property(e => e.UpdateOn)
                    .HasColumnType("datetime")
                    .HasColumnName("updateOn");

                entity.Property(e => e.UpdatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("updatedBy");

                entity.HasOne(d => d.Module)
                    .WithMany(p => p.PackageModule)
                    .HasForeignKey(d => d.ModuleId)
                    .HasConstraintName("FK_PackageModule_Module");

                entity.HasOne(d => d.Package)
                    .WithMany(p => p.PackageModule)
                    .HasForeignKey(d => d.PackageId)
                    .HasConstraintName("FK_PackageModule_Package");
            });

            modelBuilder.Entity<Role>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("createdBy");

                entity.Property(e => e.CreatedOn)
                    .HasColumnType("datetime")
                    .HasColumnName("createdOn");

                entity.Property(e => e.Role1)
                    .HasMaxLength(100)
                    .HasColumnName("role");

                entity.Property(e => e.UpdateOn)
                    .HasColumnType("datetime")
                    .HasColumnName("updateOn");

                entity.Property(e => e.UpdatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("updatedBy");
            });

            modelBuilder.Entity<RoleModule>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("createdBy");

                entity.Property(e => e.CreatedOn)
                    .HasColumnType("datetime")
                    .HasColumnName("createdOn");

                entity.Property(e => e.ModuleId).HasColumnName("moduleId");

                entity.Property(e => e.RoleId).HasColumnName("roleId");

                entity.Property(e => e.UpdateOn)
                    .HasColumnType("datetime")
                    .HasColumnName("updateOn");

                entity.Property(e => e.UpdatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("updatedBy");

                entity.HasOne(d => d.Module)
                    .WithMany(p => p.RoleModule)
                    .HasForeignKey(d => d.ModuleId)
                    .HasConstraintName("FK_RoleModule_Module");

                entity.HasOne(d => d.Role)
                    .WithMany(p => p.RoleModule)
                    .HasForeignKey(d => d.RoleId)
                    .HasConstraintName("FK_RoleModule_Role");
            });

            modelBuilder.Entity<SystemUser>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("createdBy");

                entity.Property(e => e.CreatedOn)
                    .HasColumnType("datetime")
                    .HasColumnName("createdOn");

                entity.Property(e => e.IsActive).HasColumnName("isActive");

                entity.Property(e => e.Password)
                    .HasMaxLength(200)
                    .HasColumnName("password");

                entity.Property(e => e.RoleId).HasColumnName("roleId");

                entity.Property(e => e.UpdateOn)
                    .HasColumnType("datetime")
                    .HasColumnName("updateOn");

                entity.Property(e => e.UpdatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("updatedBy");

                entity.Property(e => e.UserId).HasColumnName("userId");

                entity.HasOne(d => d.Role)
                    .WithMany(p => p.SystemUser)
                    .HasForeignKey(d => d.RoleId)
                    .HasConstraintName("FK_SystemUser_Role");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.SystemUser)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK_SystemUser_User");
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("createdBy");

                entity.Property(e => e.CreatedOn)
                    .HasColumnType("datetime")
                    .HasColumnName("createdOn");

                entity.Property(e => e.DateOfBirth)
                    .HasColumnType("datetime")
                    .HasColumnName("dateOfBirth");

                entity.Property(e => e.FirstName)
                    .HasMaxLength(200)
                    .HasColumnName("firstName");

                entity.Property(e => e.IsActive).HasColumnName("isActive");

                entity.Property(e => e.LastName)
                    .HasMaxLength(200)
                    .HasColumnName("lastName");

                entity.Property(e => e.UpdateOn)
                    .HasColumnType("datetime")
                    .HasColumnName("updateOn");

                entity.Property(e => e.UpdatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("updatedBy");

                entity.Property(e => e.Username)
                    .HasMaxLength(100)
                    .HasColumnName("username");
            });

            modelBuilder.Entity<UserContact>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.ContactTypeId).HasColumnName("contactTypeId");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("createdBy");

                entity.Property(e => e.CreatedOn)
                    .HasColumnType("datetime")
                    .HasColumnName("createdOn");

                entity.Property(e => e.IsActive).HasColumnName("isActive");

                entity.Property(e => e.UpdateOn)
                    .HasColumnType("datetime")
                    .HasColumnName("updateOn");

                entity.Property(e => e.UpdatedBy)
                    .HasMaxLength(200)
                    .HasColumnName("updatedBy");

                entity.Property(e => e.UserId).HasColumnName("userId");

                entity.HasOne(d => d.ContactType)
                    .WithMany(p => p.UserContact)
                    .HasForeignKey(d => d.ContactTypeId)
                    .HasConstraintName("FK_UserContact_ContactType");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.UserContact)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK_UserContact_User");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}