// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class Role
    {
        public Role()
        {
            InstituteUser = new HashSet<InstituteUser>();
            RoleModule = new HashSet<RoleModule>();
            SystemUser = new HashSet<SystemUser>();
        }

        public int Id { get; set; }
        public string Role1 { get; set; }
        public int? ParentRoleId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual ICollection<InstituteUser> InstituteUser { get; set; }
        public virtual ICollection<RoleModule> RoleModule { get; set; }
        public virtual ICollection<SystemUser> SystemUser { get; set; }
    }
}