// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class RoleModule
    {
        public Guid Id { get; set; }
        public Guid? RoleId { get; set; }
        public Guid? ModuleId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual Module Module { get; set; }
        public virtual Role Role { get; set; }
    }
}