// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class Status
    {
        public Status()
        {
            InstituteAssignmentSubmission = new HashSet<InstituteAssignmentSubmission>();
            SupportTicket = new HashSet<SupportTicket>();
        }

        public int Id { get; set; }
        public string StatusText { get; set; }
        public string StatueTypeCode { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual ICollection<InstituteAssignmentSubmission> InstituteAssignmentSubmission { get; set; }
        public virtual ICollection<SupportTicket> SupportTicket { get; set; }
    }
}