// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class StudentAttendance
    {
        public long Id { get; set; }
        public long InstituteId { get; set; }
        public long InstituteUserId { get; set; }
        public long InstituteUserClassId { get; set; }
        public DateTime RecordDate { get; set; }
        public bool IsAttendance { get; set; }
        public long ResponsibleUserId { get; set; }
        public long InstituteClassId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }
    }
}