// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class SupportTicket
    {
        public SupportTicket()
        {
            SupportTicketConversation = new HashSet<SupportTicketConversation>();
        }

        public long Id { get; set; }
        public string Subject { get; set; }
        public string IssueText { get; set; }
        public long? RaisedBy { get; set; }
        public DateTime? RaisedOn { get; set; }
        public long InstituteId { get; set; }
        public int? StatusId { get; set; }
        public long? AssignedUserId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual Institute Institute { get; set; }
        public virtual InstituteUser RaisedByNavigation { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<SupportTicketConversation> SupportTicketConversation { get; set; }
    }
}