// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class SupportTicketConversation
    {
        public long Id { get; set; }
        public long? SupportTicketId { get; set; }
        public string ConversationText { get; set; }
        public long ReplyBy { get; set; }
        public DateTime? ReplyOn { get; set; }
        public bool IsAdminReply { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual SupportTicket SupportTicket { get; set; }
    }
}