// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class User
    {
        public User()
        {
            CalenderEvent = new HashSet<CalenderEvent>();
            InstituteUser = new HashSet<InstituteUser>();
            SystemUser = new HashSet<SystemUser>();
            UserContact = new HashSet<UserContact>();
        }

        public long Id { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string Password { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual ICollection<CalenderEvent> CalenderEvent { get; set; }
        public virtual ICollection<InstituteUser> InstituteUser { get; set; }
        public virtual ICollection<SystemUser> SystemUser { get; set; }
        public virtual ICollection<UserContact> UserContact { get; set; }
    }
}