// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ParentCheck.Data
{
    public partial class UserContact
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public int ContactTypeId { get; set; }
        public string ContactValue { get; set; }
        public bool IsPrimary { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdateOn { get; set; }

        public virtual ContactType ContactType { get; set; }
        public virtual User User { get; set; }
    }
}